---
# file: roles/rehabstod/tasks/main.yml

- name: stop tomcat
  service: name={{ tomcat_service }} state=stopped pattern={{ tomcat_service }}

- name: create release directory
  file: path={{ releases_folder }} state=directory

#- name: Make sure liquibase runner file download is forced when using shapshot repo
#  file: state=absent  path={{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip
#  when: repo == "snapshots"

#- name: download liquibase-runner-{{ version }}.zip
#  get_url: url=https://build-inera.nordicmedtest.se/nexus/content/repositories/{{ repo }}/se/inera/rehabstod/rehabstod-liquibase-runner/{{ version }}/rehabstod-liquibase-runner-{{ version }}.zip
#      dest={{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip

#- name: Unzip liquibase-runner-{{ version }}.zip
#  command: unzip -od {{ releases_folder }} {{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip
#  args:
#    creates: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}/bin/liquibase-runner"

#- name: run liquibase update
#  command: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}/bin/rehabstod-liquibase-runner --url={{ database_url }} --username={{ database_username }} --password={{ database_password }} update"
#  args:
#      chdir: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}"
#  environment:
#      JAVA_HOME: "{{ java_home }}"

- name: Make sure rehabstod-web file download is forced when using shapshots repo
  file: state=absent  path={{ releases_folder }}/rehabstod-web-{{ version }}.war
  when: repo == "snapshots"

- name: Download rehabstod-web-{{ version }}.war
  get_url: url=https://build-inera.nordicmedtest.se/nexus/content/repositories/{{ repo }}/se/inera/intyg/rehabstod/rehabstod-web/{{ version }}/rehabstod-web-{{ version }}.war
      dest={{ releases_folder }}/rehabstod-web-{{ version }}.war
      timeout=60

- name: remove old version of unpacked rehabstod war
  file: state=absent
      path={{ webapps_folder }}/ROOT

- name: remove old version of ROOT.war
  file: state=absent
      path={{ webapps_folder }}/ROOT.war

- name: Deploy rehabstod-web-{{ version }}.war as ROOT.war in {{ webapps_folder }}
  command: cp {{ releases_folder }}/rehabstod-web-{{ version }}.war {{ webapps_folder }}/ROOT.war

- name: Create version file
  template: src=version.txt.j2 dest={{ webapps_folder }}/version.txt

- name: update configuration to {{ config_version }}
  git: repo={{ config_repository }}
       dest={{ config_folder }}
       version={{ config_version }}

- name: start tomcat
  service: name={{ tomcat_service }} state=started pattern={{ tomcat_service }}
