apiVersion: v1
data:
  NTJP_WS_CERTIFICATE_TYPE: JKS
  NTJP_WS_TRUSTSTORE_TYPE: JKS
  SAML_KEYSTORE_ALIAS: 'verifiering.rehabstod.intygstjanster.sjunet.org'
  SPARRTJANST_CHECKBLOCKS_ENDPOINT_URL: 'http://localhost:8080/services/stubs/informationsecurity/authorization/blocking/CheckBlocks/4/rivtabp21'
  SAMTYCKESTJANST_CHECKCONSENT_ENDPOINT_URL: 'http://localhost:8080/services/stubs/informationsecurity/authorization/consent/CheckConsent/2/rivtabp21'
  SAMTYCKESTJANST_REGISTEREXTENDEDCONSENT_ENDPOINT_URL: 'http://localhost:8080/services/stubs/informationsecurity/authorization/consent/RegisterExtendedConsent/2/rivtabp21'
  STATISTIK_SSO_URL:Â 'https://statistik-demo-demointyg.app-test1.ind-ocp.sth.basefarm.net/net/oauth/token/view'
kind: ConfigMap
metadata:
  name: rehabstod-demo-configmap-envvar
type: Opaque
